name = "OptimumPathCrack"
uuid = "c3626293-3405-4dff-8bb8-79fc30f88619"
authors = ["Carmona <carmona@fisica.ufc.br> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
